config/routes.rb
Rails.application.routes.draw do
 
  resources :document_types
  resources :rols
  resources :documents
  devise_for :users
  resources :actividads do 
        get :get_events, on: :collection
  end
  	
  
  root 'welcome#home'
    
  get "misactividades", to: "actividads#get_act", as: "get_act"
   get "actividades_cerradas", to: "actividads#actividades_cerradas", as: "actividades_cerradas"
  get "actividades", to: "actividads#set_act" , as: "set_act"
  get "user_actividades/:user", to: "actividads#user_actividades" , as: "user_actividades"
  get "usuarios", to: "actividads#usuarios" , as: "usuarios"
  get "actividades_invitado", to: "actividads#invitado" , as: "invitado"
  get "new_seguimiento/:actividad", to: "actividads#new_seguimiento" , as: "new_seguimiento"
  post "create_seguimiento", to: "actividads#create_seguimiento" , as: "create_seguimiento"
  post "create_document", to: "documents#create_document" , as: "create_document"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rol.rb
# == Schema Information
#
# Table name: rols
#
#  id           :integer          not null, primary key
#  name         :string
#  description  :text
#  act_admin    :boolean
#  act_basico   :boolean
#  act_director :boolean
#  doc_admin    :boolean
#  doc_basico   :boolean
#  doc          :string
#  director     :boolean
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Rol < ApplicationRecord
	has_many :users
end

app/controllers/rols_controller.rb
class RolsController < ApplicationController
  before_action :set_rol, only: [:show, :edit, :update, :destroy]

  # GET /rols
  # GET /rols.json
  def index
    @rols = Rol.all
  end

  # GET /rols/1
  # GET /rols/1.json
  def show
  end

  # GET /rols/new
  def new
    @rol = Rol.new
  end

  # GET /rols/1/edit
  def edit
  end

  # POST /rols
  # POST /rols.json
  def create
    @rol = Rol.new(rol_params)

    respond_to do |format|
      if @rol.save
        format.html { redirect_to @rol, notice: 'Rol was successfully created.' }
        format.json { render :show, status: :created, location: @rol }
      else
        format.html { render :new }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rols/1
  # PATCH/PUT /rols/1.json
  def update
    respond_to do |format|
      if @rol.update(rol_params)
        format.html { redirect_to @rol, notice: 'Rol was successfully updated.' }
        format.json { render :show, status: :ok, location: @rol }
      else
        format.html { render :edit }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rols/1
  # DELETE /rols/1.json
  def destroy
    @rol.destroy
    respond_to do |format|
      format.html { redirect_to rols_url, notice: 'Rol was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rol
      @rol = Rol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rol_params
      params.require(:rol).permit(:name, :description, :act_admin, :act_basico, :act_director, :doc_admin, :doc_basico, :doc, :director)
    end
end

app/helpers/rols_helper.rb
module RolsHelper
end

app/views/rols/_form.html.erb
<%= form_for(rol) do |f| %>
  <% if rol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rol.errors.count, "error") %> prohibited this rol from being saved:</h2>

      <ul>
      <% rol.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-md-6 form-group">
    <%= f.label "Nombre" %>
    <%= f.text_field :name, class:"form-control" %>
  </div>

  <div class="col-md-6 form-group">
    <%= f.label "Descripcion" %>
    <%= f.text_area :description, class:"form-control" %>
  </div>
</div>

<div class="row">
  <div class="col-md-2 form-group">
    <%= f.label :act_admin %>
    <%= f.check_box :act_admin %>
  </div>

  <div class="col-md-2 form-group">
    <%= f.label :act_basico %>
    <%= f.check_box :act_basico %>
  </div>

  <div class="col-md-2  form-group">
    <%= f.label :act_director %>
    <%= f.check_box :act_director %>
  </div>

  <div class="col-md-2 form-group">
    <%= f.label :doc_admin %>
    <%= f.check_box :doc_admin %>
  </div>

  <div class="col-md-2 form-group">
    <%= f.label :doc_basico %>
    <%= f.check_box :doc_basico %>
  </div>


  <div class="col-md-2 form-group">
    <%= f.label "Doc Director" %>
    <%= f.check_box :director %>
  </div>
</div>
  

  <div class="actions">
    <%= f.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rols/edit.html.erb
<h1>Editing Rol</h1>

<%= render 'form', rol: @rol %>

<%= link_to 'Show', @rol %> |
<%= link_to 'Back', rols_path %>

app/views/rols/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rols</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Act admin</th>
      <th>Act basico</th>
      <th>Act director</th>
      <th>Doc admin</th>
      <th>Doc basico</th>
      <th>Doc</th>
      <th>Director</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rols.each do |rol| %>
      <tr>
        <td><%= rol.name %></td>
        <td><%= rol.description %></td>
        <td><%= rol.act_admin %></td>
        <td><%= rol.act_basico %></td>
        <td><%= rol.act_director %></td>
        <td><%= rol.doc_admin %></td>
        <td><%= rol.doc_basico %></td>
        <td><%= rol.doc %></td>
        <td><%= rol.director %></td>
        <td><%= link_to 'Show', rol %></td>
        <td><%= link_to 'Edit', edit_rol_path(rol) %></td>
        <td><%= link_to 'Destroy', rol, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rol', new_rol_path %>

app/views/rols/new.html.erb
<h1>Nuevo  Rol</h1>

<%= render 'form', rol: @rol %>

<%= link_to 'Back', rols_path %>

app/views/rols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rol.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @rol.description %>
</p>

<p>
  <strong>Act admin:</strong>
  <%= @rol.act_admin %>
</p>

<p>
  <strong>Act basico:</strong>
  <%= @rol.act_basico %>
</p>

<p>
  <strong>Act director:</strong>
  <%= @rol.act_director %>
</p>

<p>
  <strong>Doc admin:</strong>
  <%= @rol.doc_admin %>
</p>

<p>
  <strong>Doc basico:</strong>
  <%= @rol.doc_basico %>
</p>

<p>
  <strong>Doc:</strong>
  <%= @rol.doc %>
</p>

<p>
  <strong>Director:</strong>
  <%= @rol.director %>
</p>

<%= link_to 'Edit', edit_rol_path(@rol) %> |
<%= link_to 'Back', rols_path %>