config/routes.rb
Rails.application.routes.draw do
 
  resources :document_types
  resources :rols
  resources :documents
  devise_for :users
  resources :actividads do 
        get :get_events, on: :collection
  end
  	
  
  root 'welcome#home'
    
  get "misactividades", to: "actividads#get_act", as: "get_act"
   get "actividades_cerradas", to: "actividads#actividades_cerradas", as: "actividades_cerradas"
  get "actividades", to: "actividads#set_act" , as: "set_act"
  get "user_actividades/:user", to: "actividads#user_actividades" , as: "user_actividades"
  get "usuarios", to: "actividads#usuarios" , as: "usuarios"
  get "actividades_invitado", to: "actividads#invitado" , as: "invitado"
  get "new_seguimiento/:actividad", to: "actividads#new_seguimiento" , as: "new_seguimiento"
  post "create_seguimiento", to: "actividads#create_seguimiento" , as: "create_seguimiento"
  post "create_document", to: "documents#create_document" , as: "create_document"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/document_types_controller.rb
class DocumentTypesController < ApplicationController
  before_action :set_document_type, only: [:show, :edit, :update, :destroy]

  # GET /document_types
  # GET /document_types.json
  def index
    @document_types = DocumentType.all
  end

  # GET /document_types/1
  # GET /document_types/1.json
  def show
  end

  # GET /document_types/new
  def new
    @document_type = DocumentType.new
  end

  # GET /document_types/1/edit
  def edit
  end

  # POST /document_types
  # POST /document_types.json
  def create
    @document_type = DocumentType.new(document_type_params)

    respond_to do |format|
      if @document_type.save
        format.html { redirect_to @document_type, notice: 'Document type was successfully created.' }
        format.json { render :show, status: :created, location: @document_type }
      else
        format.html { render :new }
        format.json { render json: @document_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /document_types/1
  # PATCH/PUT /document_types/1.json
  def update
    respond_to do |format|
      if @document_type.update(document_type_params)
        format.html { redirect_to @document_type, notice: 'Document type was successfully updated.' }
        format.json { render :show, status: :ok, location: @document_type }
      else
        format.html { render :edit }
        format.json { render json: @document_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /document_types/1
  # DELETE /document_types/1.json
  def destroy
    @document_type.destroy
    respond_to do |format|
      format.html { redirect_to document_types_url, notice: 'Document type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document_type
      @document_type = DocumentType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_type_params
      params.require(:document_type).permit(:nombre, :codigo, :frecuencia, :user_id)
    end
end

app/helpers/document_types_helper.rb
module DocumentTypesHelper
end

app/views/document_types/_form.html.erb
<%= form_for(document_type) do |f| %>
  <% if document_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document_type.errors.count, "error") %> prohibited this document_type from being saved:</h2>

      <ul>
      <% document_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nombre %>
    <%= f.text_field :nombre, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :codigo %>
    <%= f.text_field :codigo, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :frecuencia %>
    <%= f.number_field :frecuencia, class: "form-control" %>
  </div>

  
    <%= f.hidden_field :user_id, value: current_user.id %>
  

  <div class="actions">
    <%= f.submit "Guardar", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/document_types/edit.html.erb
<h1>Editing Document Type</h1>

<%= render 'form', document_type: @document_type %>

<%= link_to 'Show', @document_type %> |
<%= link_to 'Back', document_types_path %>

app/views/document_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipos de documentos</h1>

<table class = "table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Codigo</th>
      <th>Frecuencia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @document_types.each do |document_type| %>
      <tr>
        <td><%= document_type.nombre %></td>
        <td><%= document_type.codigo %></td>
        <td><%= document_type.frecuencia %></td>
     
        <td><%= link_to 'Ver', document_type %></td>
        <td><%= link_to 'Editar', edit_document_type_path(document_type) %></td>
        <td><%= link_to 'Borrar', document_type, method: :delete, data: { confirm: 'Esta Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Tipo de Documento', new_document_type_path,class: "btn btn-primary" %>

app/views/document_types/new.html.erb
<h1>Nuevo Tipo de Documento</h1>

<%= render 'form', document_type: @document_type %>

<%= link_to 'Back', document_types_path %>

app/views/document_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @document_type.nombre %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @document_type.codigo %>
</p>

<p>
  <strong>Frecuencia:</strong>
  <%= @document_type.frecuencia %>
</p>

<p>
  <strong>User:</strong>
  <%= @document_type.user_id %>
</p>

<%= link_to 'Edit', edit_document_type_path(@document_type) %> |
<%= link_to 'Back', document_types_path %>