config/routes.rb
Rails.application.routes.draw do
 
  resources :document_types
  resources :rols
  resources :documents
  devise_for :users
  resources :actividads do 
        get :get_events, on: :collection
  end
  	
  
  root 'welcome#home'
    
  get "misactividades", to: "actividads#get_act", as: "get_act"
   get "actividades_cerradas", to: "actividads#actividades_cerradas", as: "actividades_cerradas"
  get "actividades", to: "actividads#set_act" , as: "set_act"
  get "user_actividades/:user", to: "actividads#user_actividades" , as: "user_actividades"
  get "usuarios", to: "actividads#usuarios" , as: "usuarios"
  get "actividades_invitado", to: "actividads#invitado" , as: "invitado"
  get "new_seguimiento/:actividad", to: "actividads#new_seguimiento" , as: "new_seguimiento"
  post "create_seguimiento", to: "actividads#create_seguimiento" , as: "create_seguimiento"
  post "create_document", to: "documents#create_document" , as: "create_document"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actividad.rb
# == Schema Information
#
# Table name: actividads
#
#  id             :integer          not null, primary key
#  consecutivo    :integer
#  tipo           :string
#  user_id        :integer
#  prioridad      :string
#  responsable_id :integer
#  nombre         :string
#  descripcion    :text
#  anexo          :string
#  f_entrega      :date
#  porcentaje     :integer
#  estado_cierre  :boolean
#  estado_envio   :boolean
#  contador       :integer
#  codigo         :string
#  e_vencimiento  :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  balon          :string
#

class Actividad < ApplicationRecord
    has_and_belongs_to_many :users
	belongs_to :responsable, :class_name => 'User'
	belongs_to :user, :class_name => 'User'
	has_many :seguimientos
    mount_uploader :anexo, AnexoActividadUploader
	after_save :enviar
    validates :f_entrega, presence: true
    validates :responsable_id, presence: true


scope :estado_f, -> { where(estado_cierre: false).order(created_at: :desc) }




def self.search(search, search1, search2)

if search2 == "Proxima"
search2 = "Proxima a Vencer"
end
            search1 != "" ? (scope :responsable, -> { where(responsable_id: search1) }) : (scope :responsable, -> { where.not(responsable_id: nil) })
             search2 != "" ? (scope :estado, -> { where(e_vencimiento: search2) }) : (scope :estado, -> { where.not(e_vencimiento: nil) })  
            responsable.estado#.where("nombre like '%#{search}%' or descripcion like '%#{search}%' "  )  
        end
    

def enviar

	   if self.estado_envio && (self.e_vencimiento != "Vigente" &&  self.e_vencimiento != "Proxima a Vencer" &&  self.e_vencimiento != "Vencida")
        user = User.find(self.responsable_id)
        @times = self.f_entrega.to_time
        @time =  @times.to_i - Time.now.to_i  
        self.contador = (@time / 60 / 60/ 24) + 1
        self.e_vencimiento = "Vigente"
        save
        ActividadMailer.creacion(user,self).deliver
        self.users.each do |user|
                
                ActividadMailer.invitado(user,self).deliver
        


        end
      end

      end
 
end

app/controllers/actividads_controller.rb
class ActividadsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_actividad, only: [:show, :edit, :update, :destroy]

  # GET /actividads
  # GET /actividads.json

 respond_to :json
  def get_events
if current_user.rol.act_admin
    @task = Actividad.all
    events = []
    @task.each do |task|
      if task.e_vencimiento == "Vigente"
        @color = "green"
      elsif task.e_vencimiento == "Proxima a Vencer"

      @color = "orange" 
      else
        
          @color = "red"
      end
      events << {:id => task.id, :title => "#{task.nombre} ", :start => "#{task.f_entrega}" , :color => "#{@color}"}
    end
    render :text => events.to_json

else

 
    @task = Actividad.where(responsable_id: current_user.id)
    events = []
    @task.each do |task|
      if task.e_vencimiento == "Vigente"
        @color = "green"
      else
          @color = "red"
      end
      events << {:id => task.id, :title => "#{task.nombre} ", :start => "#{task.f_entrega}" , :color => "#{@color}"}
    end
    render :text => events.to_json
end


  end




def user_actividades

if params[:search] || params[:search1] || params[:search2]
    @actividads = Actividad.estado_f.where(responsable_id:params[:user]).search(params[:search],params[:search1],params[:search2])
  else
      @actividads = Actividad.estado_f.where(responsable_id:params[:user])
  end
user = User.find(params[:user])
    @tipo = "#{user.nombres} #{user.apellidos}"
    @resp = "n/a"
    @route = user_actividades_path
render "index"

end


def actividades_cerradas

if params[:search] || params[:search1] || params[:search2]
  
  if current_user.rol.act_admin

    @actividads = Actividad.where(estado_cierre: true).search(params[:search],params[:search1],params[:search2])
  elsif current_user.rol.act_director
      
    @actividads = Actividad.where(estado_cierre: true).where(user_id: current_user.id).or(where(responsable_id: current_user.id)).search(params[:search],params[:search1],params[:search2])


    else
     @actividads = Actividad.where(estado_cierre: true).where(responsable_id: current_user.id).search(params[:search],params[:search1],params[:search2])


     end

  else
      @actividads = Actividad.where(estado_cierre: true)
  end


    @tipo = "Actividades Cerradas"
    @resp = "n/a"
    @route = actividades_cerradas_path
render "index"

end




def usuarios
@users = User.all


end












    def index
    if current_user.rol.act_admin

    
    if params[:search] || params[:search1] || params[:search2]
    @actividads = Actividad.estado_f.search(params[:search],params[:search1],params[:search2])
  else
      @actividads = Actividad.estado_f
  end

    @tipo = "Todas las Actividades"
    @resp = "n/a"
    @route = actividads_path
  else
    redirect_to get_act_path
  end


  end
   def get_act
    if params[:search] || params[:search1] || params[:search2]
           @actividads = Actividad.where(responsable_id: current_user.id).estado_f.search(params[:search],params[:search1],params[:search2])
  else
           @actividads = Actividad.where(responsable_id: current_user.id).estado_f

  end
    @tipo = "Mis Actividades"
    @resp = "resp"
    @route = get_act_path
    render "index"
  end




    def invitado
 if params[:search] || params[:search1] || params[:search2]
     @actividads = current_user.actividads.where(estado_envio: true).estado_f.search(params[:search],params[:search1],params[:search2])
   else 
     @actividads = current_user.actividads.where(estado_envio: true).estado_f
    end
    @tipo = "Actividades Invitado"
    @resp = "n/a"
    @route = invitado_path
    render "index"

  end




 def set_act
    if current_user.rol.act_director ||  current_user.rol.act_admin
if params[:search] || params[:search1] || params[:search2]
    @actividads = Actividad.where(user_id: current_user.id).estado_f.search(params[:search],params[:search1],params[:search2])
     else
 @actividads = Actividad.where(user_id: current_user.id).estado_f
     end



     @tipo = "Actividades que asigne"
     @resp = "asig"
      @route = set_act_path
      else
    redirect_to get_act_path
   
  end
render "index"
end

def show
  end

  def new
    @actividad = Actividad.new


 #  console.log(zohoalejovm10view295.Lista_Empleados);
  #  $scope.nombre = zohoalejovm10view295.Lista_Empleados[0].NOMBRES;





end
  # GET /actividads/1/edit
  def edit
  end

  # POST /actividads
  # POST /actividads.json
  def create
    @actividad = Actividad.new(actividad_params)
    @actividad.estado_cierre  = false
    num = Actividad.maximum(:consecutivo)
    if num != nil
        num = num + 1

    else
        num = 1001
    end
    @actividad.consecutivo = num
    @actividad.balon = "responsable"
     @actividad.e_vencimiento = "Sin Enviar"
    respond_to do |format|
      if @actividad.save
        
        format.html { redirect_to @actividad, notice: 'Actvidad was successfully created.' }
        format.json { render :show, status: :created, location: @actvidad }
      else
        format.html { render :new }
        format.json { render json: @actividad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actividads/1
  # PATCH/PUT /actividads/1.json
  def update
    respond_to do |format|
      if @actividad.update(actividad_params)
        format.html { redirect_to @actividad, notice: 'Actividad was successfully updated.' }
        format.json { render :show, status: :ok, location: @actividad }
      else
        format.html { render :edit }
        format.json { render json: @actividad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actividads/1
  # DELETE /actividads/1.json
  def destroy
    @actividad.destroy
    respond_to do |format|
      format.html { redirect_to actividads_url, notice: 'Actividad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



def new_seguimiento
  @actividad = Actividad.find(params[:actividad])
end

def create_seguimiento

  @seguimiento = Seguimiento.create(user_id:params[:user_id],actividad_id:params[:actividad_id],descripcion:params[:descripcion],porcentaje:params[:porcentaje],cierre:params[:cierre],anexo: params[:anexo])

if @seguimiento.save

redirect_to actividad_path(@seguimiento.actividad_id)

else
redirect_to root_path
  end
  end

private
def get_tipo(x)
    if x == "Actividad"
                "ACT"
    elsif x == "Peticion"
                   "PET" 
    elsif x == "Queja"
                "QUE"
    elsif x == "Reclamo"
                    "REC"
    elsif x == "Felicitaciones"
                    "FEL"
      elsif x == "Solicitud"
                    "SOL"

  end
end






  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actividad
      @actividad = Actividad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actividad_params
      params.require(:actividad).permit(:consecutivo, :tipo, :user_id, :balon,:prioridad, :responsable_id, :nombre, :descripcion, :anexo, :f_entrega, :porcentaje, :estado_envio, :contador, :codigo, :e_vencimiento, :user_ids => [])
    end
end

app/helpers/actividads_helper.rb
module ActividadsHelper
end

app/views/actividads/_form.html.erb
<%= form_for(actividad) do |f| %>
  <% if actividad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actividad.errors.count, "error") %> prohibited this actvidad from being saved:</h2>

      <ul>
      <% actividad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
<div class="row">
  <div class="col-md-3">
    
  <div class="form-group">
    <%= f.label :tipo %>
     <%= f.select 'tipo', options_for_select(["Actividad", "Peticion", "Queja", "Reclamo", "Solicitud","Felicitaciones", "Oportunidad de Negocio"]), {},{:class => 'form-control'}%>
  </div>
  </div>
  <div class="col-md-3">
      <div class="form-group">
    <%= f.label :responsable_id %>
   <%= f.select :responsable_id,
   User.all.map { |u| ["#{u.nombres} #{u.apellidos}", u.id] },
               { include_blank: false },
               { class: 'form-control chosen-select' }
%>
  </div>

  </div>
 <div class="col-md-6">
    
     <div class="form-group">
               <%= f.label "Otros interesados" %>
               <%= f.select :user_ids, User.all.collect {|c| ["#{c.nombres} #{c.apellidos}", c.id]}, {prompt: false}, {:multiple => true,class: 'form-control chosen-mselect'} %>
      </div>
   </div>
   </div>
   <div class="row">
  <div class="col-md-3">
    
  <div class="form-group">
    <%= f.label :prioridad %>
     <%= f.select 'prioridad', options_for_select(["Alta", "Media","Baja"]), {},{:class => 'form-control'}%>
  </div>

  </div>
  <div class="col-md-3">
    <div class="form-group">
    <%= f.label :f_entrega %>
    <%= f.date_field :f_entrega, class:"form-control"  %>
  </div>
    
  </div>
  <div class="col-md-3">
    <div class="form-group">
    <%= f.label :anexo %>
    <%= f.file_field :anexo , class:"form-control" %>
  </div>
  </div>
    <div class="col-md-6">
    <div class="form-group">
    <%= f.label "Nombre de la Actividad" %>
    <%= f.text_field :nombre, class:"form-control"  %>
  </div>
  </div>
    <div class="col-md-2">
    
  <div class="form-group">
    <%= f.label "Enviar" %>
    <%= f.check_box :estado_envio, {:checked=>true , class:"form-control"} %>
  </div>
  </div>
 
  <div class="col-md-9">
     <div class="form-group">
    <%= f.label :descripcion %>
    <%= f.text_area :descripcion, class: 'ck'  %>
  </div>

  </div>
 

</div>



  


  
 <%= f.hidden_field :user_id , :value => current_user.id %>
 
  
<script>
    $('.chosen-mselect').chosen(
        {

          allow_single_deselect: true,
          no_results_text: 'No hay resultados',
          width: '350px;',
          placeholder_text_single: "Seleccione una opción",
          placeholder_text_multiple: "Seleccione una varias opciones"

        });
      $('.chosen-select').chosen(
        {

          allow_single_deselect: true,
          no_results_text: 'No hay resultados',
          width: '200px;',
          placeholder_text_single: "Seleccione una opción",
          placeholder_text_multiple: "Seleccione una varias opciones"

        });
</script>




  


  

  <div class="actions">
    <%= f.submit "Guardar",class: "btn btn-primary"  %>
  </div>
<% end %>

app/views/actividads/_form_seguimiento.html.erb
<div id="contact-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Crear Seguimiento</h4>
      </div>
<%= form_tag create_seguimiento_path, :multipart => true do %>
  <div class="alert alert-danger" style="display:none;padding: 10px;">
    <ul>
    
    </ul>
  </div>
      <div class="modal-body">
<div class="row">
  <div class="col-md-12">
     <div class="form-group">
    <%= label_tag "Descripcion" %>
    <%= text_area_tag :descripcion, nil , class: "form-control formus" %>
  </div>
   <div class="form-group">
    <%= label_tag "Anexo" %>
    <%= file_field_tag :anexo ,  class: "form-control formus" %>
  </div>
  <div class="form-group">
    <%= label_tag "Porcentaje de Avance" %>
    <%= number_field_tag :porcentaje, nil , class: "form-control formus" %>
  </div>
    <%if current_user.id == @actividad.user_id%>
       <div class="form-group">
                  <label class="label-check" style = "margin-right:10px;display:inline-block">Cerrar</label>
                  <%= check_box_tag :cierre ,nil,nil, class: "check-box" %>
      </div>
<%end%>

  </div>
</div>

        



<%= hidden_field_tag :user_id ,current_user.id %>

<%= hidden_field_tag :actividad_id ,@actividad.id %>


 
<br>

      <div class="modal-footer text-center">
       
        <%= submit_tag "Guardar", class: 'btn btn-primary btnpad' %>
         <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
      </div>
<% end %>

    </div>
  </div>
</div>
</div>

app/views/actividads/edit.html.erb
<h1>Editing Actividad</h1>

<%= render 'form', actividad: @actividad %>

<%= link_to 'Show', @actividad %> |
<%= link_to 'Back', actividads_path %>

app/views/actividads/index.html.erb
<div class="row">
  <div class="col-md-8">
<h2 class= "color-blue"><%=@tipo%>(<%=@actividads.count%>)</h2>    
  </div>
  <div class="col-md-4 text-right">
  <%if current_user.rol.act_admin  || current_user.rol.act_director %>
    <%= link_to 'Nueva Actividad', new_actividad_path, class:"btn btn-primary" %>
    <%end%>
  </div>
</div>
<div class="row busqueda">
   <div class="col-md-12">
<%= form_tag(@route, :method => "get", id: "search-form") do %>
         <!--<%= text_field_tag :search, params[:search], placeholder: "Ingresa texto", class: "form-control search" %>-->
          <%=select_tag 'search1', options_for_select(User.all.collect{ |u| ["#{u.nombres} #{u.apellidos}", u.id, ] }),{:class => "form-control sh1", include_blank: true }%>
          <%= select_tag 'search2', options_for_select(["Vigente", "Proxima", "Vencida"]),{:class => 'form-control sh2', include_blank: true }%>

         <%= submit_tag "Buscar", :class => "btn btn-primary" %>
         <% end %>

  </div>  </div>


    <% @actividads.each do |actividad| %>


  <p class = "p"><%=  (image_tag "https://www.ecured.cu/images/thumb/7/7a/PELOTA_TENIS.jpg/260px-PELOTA_TENIS.jpg", style:"width:30px") if (@resp == "resp" && actividad.balon == "responsable")%><%=  (image_tag "https://www.ecured.cu/images/thumb/7/7a/PELOTA_TENIS.jpg/260px-PELOTA_TENIS.jpg", style:"width:30px") if (@resp == "asig" && actividad.balon == "asignador")%> |
    <%= link_to 'Editar', edit_actividad_path(actividad) %> |
    <%= link_to 'Eliminar', actividad, method: :delete, data: { confirm: 'Are you sure?' } %></p>
  
<%= link_to  actividad_path(actividad) do %>

      <div class="row actividad">
  

   <div class="row">
        
         
  <div class="col-md-3">
    <p><strong><%= actividad.tipo %> - <%= actividad.consecutivo %></strong></p>
  </div>
  <div class="col-md-3">
    <p><strong>F Creacion:</strong> <%= get_date(actividad.created_at)%></p>
  </div>
  <div class="col-md-3">
    <p><strong>Prioridad: </strong><%= actividad.prioridad %></p>
  </div>
  <div class="col-md-3">
    <p><strong>Asigno:</strong> <%= actividad.user.nombres %></p>
  </div>
    

 
  </div>
  <hr class="hr">
  <div class="row">
  <div class="col-md-3">
    <p><strong>Estado:</strong> <%= get_estado(actividad.estado_cierre)%> <%= "," + actividad.e_vencimiento.to_s%></p>
  </div>
    <div class="col-md-3">
    <p><strong>¿Enviada?:</strong> <%= get_envio(actividad.estado_envio)%> </p>
  </div>
    <div class="col-md-3">
    <p><strong>Avance:</strong> <%= actividad.porcentaje%> %</p>
  </div>

 
  <div class="col-md-3">
    <p><strong>Responsable:</strong> <%= actividad.responsable.nombres %> </p>
  </div>
 
   </div>
<hr class="hr">
  <div class="row">
 <div class="col-md-6">
    <p><strong>Actividad: </strong><%= actividad.nombre%> </p>
  </div>
   <div class="col-md-3 <%=get_venci(actividad.e_vencimiento)%>" >
    <p><strong>F Entrega:</strong> <%= get_date(actividad.f_entrega) %></p>
  </div>
  <div class="col-md-3">

    <p><strong>Anexo:</strong> <%= (link_to "Anexo.#{actividad.anexo.file.extension }", actividad.anexo_url , style:"color:#357ebd") if actividad.anexo_url %> </p>       
  </div>
  </div>
</div>
<br>
    <% end %>

    <% end %>
 





<script>

     $('.sh1').val(<%=params[:search1]%>) ;
     $('.sh2').val(<%=params[:search2]%>) ;



</script>

<style>
   .shi
   {
   height:  30px !important;
   color:gray !important;
   font-size: 10px !important;
   }
   .shi1
   {
   width: 60px;
   display: inline-block;
   height:  30px !important;
   color:gray !important;
   font-size: 10px !important;
   padding: 6px 2px;
   text-align: center;
   }
   .busqueda
   {
        display: block;
    padding: 10px;
    background: #e8e8e8;
   }
   .search
{
  width:200px !important;
  height: 27px!important;
  display:inline-block !important;
}

</style>

app/views/actividads/new.html.erb
<h1>New Actividad</h1>

<%= render 'form', actividad: @actividad %>

<%= link_to 'Back', actividads_path %>

app/views/actividads/new_seguimiento.js.erb
$('<%= j render "form_seguimiento", actividad: @actividad %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/actividads/show.html.erb
<%= link_to actividads_path do %>
<i class="fa fa-arrow-circle-left" aria-hidden="true" style = "font-size:26px;color:#2eb7ff"></i>
<%end%>

      <div class="row actividad">

   <div class="row">
        
         
  <div class="col-md-3">
    <p><strong><%= @actividad.tipo %>-<%= @actividad.consecutivo %></strong></p>
  </div>
   <div class="col-md-3">
    <p><strong>Consecutivo:</strong> <%= get_date(@actividad.created_at) %></p>
  </div>
  <div class="col-md-3">
    <p><strong>Prioridad: </strong><%= @actividad.prioridad %></p>
  </div>
  <div class="col-md-3">
    <p><strong>Asigno: </strong><%= @actividad.user.nombres%> </p>
  </div>
  </div>
  <hr class="hr">

 <div class="row">
    <div class="col-md-3">
    <p><strong>Estado:</strong> <%= get_estado(@actividad.estado_cierre)%></p>
  </div>
  <div class="col-md-3">
    <p><strong>¿Enviada?:</strong> <%= get_envio(@actividad.estado_envio)%> </p>
  </div>
    <div class="col-md-3">
    <p><strong>Avance:</strong> <%= @actividad.porcentaje%> %</p>
      </div>
 
  <div class="col-md-3">
    <p><strong>Responsable:</strong> <%= @actividad.responsable.nombres %> </p>
  </div>

    </div>

  <hr class="hr">

     <div class="row">
      <div class="col-md-3">
    
    <p><strong>Anexo:</strong> <%= (link_to "Anexo.#{@actividad.anexo.file.extension }", @actividad.anexo_url , style:"color:#357ebd") if @actividad.anexo_url %></p>
  </div>
  <div class="col-md-3 ">
    <p><strong>Fecha de Entrega:</strong> <%= get_date(@actividad.f_entrega) %></p>
  </div>


 
    <div class="col-md-6">
    <strong>Otros responsables:</strong> <%  @actividad.users.each do |user| %>
    <%= user.nombres%> <%= user.apellidos%>,
    <%end%>
  </div>
   </div>

  <hr class="hr">

 <div class="row">

    <div class="col-md-4">
    <p><strong>Actividad: </strong><%= @actividad.nombre%> </p>
  </div>
<div class="col-md-8">
   <div class="descnum"> <strong>Descripción:</strong> <%==   @actividad.descripcion %> </div>
  </div>
 </div>


</div>







<div class="row">
  
<%= link_to  new_seguimiento_path(@actividad), remote:true, class:"link-blanco" do %>
<h3 class="text-center segui">Seguimientos (<%=@actividad.seguimientos.count%>) 
<i class="fa fa-plus" aria-hidden="true"></i>


 </h3>
 <%end%> 
</div>

<% @actividad.seguimientos.each do |seg|%>
<div class="row actividad">
  <div class="col-md-3">
    <p><strong>Fecha:</strong> <%= get_date(seg.created_at) %></p>
  </div>
  <div class="col-md-3">
    <p><strong>Responsable:</strong> <%= seg.user.nombres %> <%= seg.user.apellidos %></p>
  </div>
  <div class="col-md-3">
    <p><strong>% de Avance: </strong><%= seg.porcentaje %></p>
  </div>
  <div class="col-md-3">
    <p><strong>Anexo:</strong> <%= (link_to "Anexo.#{seg.anexo.file.extension }", seg.anexo_url , style:"color:#357ebd") if seg.anexo_url %></p>
  </div>
 
  <div class="col-md-12">
    <p><strong>Descripción:</strong> <%= seg.descripcion %></p>
  </div>

    </div>
   <hr class="hr-10">
    <%end%>
<style>
.descnum
{
  max-height: 200px !important;
    overflow: auto;
    height: auto;
}
  
</style>

app/views/actividads/usuarios.html.erb
<div class="container-fluid">
    <div class="row">

    <%@users.order(nombres: :desc).each do |user|%>
    <%= link_to user_actividades_path(user.id) do%>
		  <%user_act = Actividad.where(responsable_id:user.id)%>
      <div class="col-md-4 perfil">
            <div class="well well-sm well1">
                <div class="media ">
                    <span class="thumbnail pull-left" href="#">
                        <% if user.avatar_url%>
                        <%= image_tag user.avatar_url(:thumb)%>
                        <%else%>
                        <img class="media-object img-perfil" src="https://legacyelitetraining.co.uk/images/users/5645.jpg"><%end%>
                    </span>
                    <div class="media-body">
                        <h4 class="media-heading"> <%= user.nombres%> <%= user.apellidos%></h4>
                		<p class="p-perfil"><span class="label label-primary">Actividades: <%=user_act.count %></span> <span class="label label-primary">Abiertas: <%= user_act.where(estado_cierre: false).count %></span> <span class="label label-primary"> Cerradas: <%= user_act.where(estado_cierre: true).count %></span></p>
                        <p class="p-perfil">
                             <span class="btn btn-xs btn-default vig"> Vig: <%= user_act.where(estado_cierre: false).where(e_vencimiento: "Vigente").count %></span>
                            <span class="btn btn-xs btn-default prox"> Prox:<%= user_act.where(estado_cierre: false).where(e_vencimiento: "Proxima a Vencer").count %></span>
                           <span class="btn btn-xs btn-default ven"> Ven: <%= user_act.where(estado_cierre: false).where(e_vencimiento: "Vencida").count %></span>
                        </p>
                        <p class="p-perfil">
                             <span class="btn btn-xs btn-default vig"> Archivos: <%= user.documents.count %></span>
                           
                        
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <%end%>

<%end%>
	</div>
</div>


<style>
.p-perfil
{
    margin: 4px !important;
}
.img-perfil
{
    width:70px !important;
}
.vig{
        background: #5ba268;
    color: white !important;

}
.prox{
        background: orange;
    color: white !important;

}
.ven
{

        background: #e86c6c;
    color: white !important;


}
.perfil
{

   -webkit-transition: box-shadow 0.3s; /* For Safari 3.1 to 6.0 */
    transition: box-shadow 0.3s;
  }

 .perfil:hover
  {
  
  
    box-shadow: rgb(136, 136, 136) 0px 0px 8px 0px;
    padding: 
  }
  .well1
  {
    margin-bottom: 0px !important;
    margin-bottom: 15px !important;

  }
</style>