config/routes.rb
Rails.application.routes.draw do
 
  resources :document_types
  resources :rols
  resources :documents
  devise_for :users
  resources :actividads do 
        get :get_events, on: :collection
  end
  	
  
  root 'welcome#home'
    
  get "misactividades", to: "actividads#get_act", as: "get_act"
   get "actividades_cerradas", to: "actividads#actividades_cerradas", as: "actividades_cerradas"
  get "actividades", to: "actividads#set_act" , as: "set_act"
  get "user_actividades/:user", to: "actividads#user_actividades" , as: "user_actividades"
  get "usuarios", to: "actividads#usuarios" , as: "usuarios"
  get "actividades_invitado", to: "actividads#invitado" , as: "invitado"
  get "new_seguimiento/:actividad", to: "actividads#new_seguimiento" , as: "new_seguimiento"
  post "create_seguimiento", to: "actividads#create_seguimiento" , as: "create_seguimiento"
  post "create_document", to: "documents#create_document" , as: "create_document"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
     <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
    <title><%= content_for?(:title) ? yield(:title) : "ActividadesV1" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
       <!--<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>-->

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body class="admin">

   <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><img  src="https://c2.staticflickr.com/4/3795/33210201395_54dcf65bff_o.png" alt=""></a>
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      
        <li><%= link_to root_path do %>
          
          <i class="fa fa-calendar" aria-hidden="true"></i> Tareas
<%end%>
<%if current_user.rol.act_admin %>
  <li><%= link_to usuarios_path do %>
          
        <i class="fa fa-user" aria-hidden="true"></i> Usuarios

<%end%>
<%end%>

  <li><%= link_to documents_path do %>
          
        <i class="fa fa-file" aria-hidden="true"></i> Documentos


<%end%>
        </li>
       </ul>
        <ul class="nav navbar-nav navbar-right">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%=current_user.nombres%> <span class="caret"></span></a>
          <ul class="dropdown-menu">
          <li><%= link_to "Cerrar Sesión" ,destroy_user_session_path, :method => :delete %></li>
            <li><%= link_to "Editar Usuario" ,edit_user_registration_path(current_user.id) %></li>
         
          </ul>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



 <ul class="nav nav-tabs" role="tablist" style = "margin-top:20px">
  <% if controller_name == "users" || controller_name == "actividads" || controller_name =="welcome"%>
              <% if current_user.rol.act_admin%>
              <li><%= link_to "Todas las Actividades", actividads_path  %></li>
                <%end%>

            

             
              <% if current_user.rol.act_admin || current_user.rol.act_director%>
              <li><%= link_to "Actividades que Asigne", set_act_path  %></li>
              <%end%>
               <li><%= link_to "Mis Actividades", get_act_path %></li>
                <li><%= link_to "Actividades Invitado", invitado_path %></li>
                 <li><%= link_to "Actividades Cerradas", actividades_cerradas_path  %></li>
              
            <%else%>              
            
              <li><%= link_to "Documentos", documents_path  %></li>
             <% if current_user.rol.act_admin || current_user.rol.act_director%>
             <li><%= link_to "Tipos Documentos", document_types_path  %></li>
                 <%end%>


              <%end%>

  </ul>
<br>
    <div class="container-fluid">
      <div class="row">
    
        <div class="col-lg-12">
   
          <%= yield %>
        </div>
        <!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>
<style>
.nav-list
{
  margin:20px 0px !important;
}
  
.well
{
  padding: 19px 10px !important;
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActividadesV1</title>
    <%= csrf_meta_tags %>
          <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = "app">
    <%= yield %>
  </body>
</html>